export const Flag: { [key: string]: string[] } = {
  '🇦🇨': ['flag-ac', 'ascension_island'],
  '🇦🇩': ['flag-ad', 'ad', 'andorra'],
  '🇦🇪': ['flag-ae', 'ae', 'united_arab_emirates'],
  '🇦🇫': ['flag-af', 'af', 'afghanistan'],
  '🇦🇬': ['flag-ag', 'ag', 'antigua_barbuda', 'antigua_&_barbuda'],
  '🇦🇮': ['flag-ai', 'ai', 'anguilla'],
  '🇦🇱': ['flag-al', 'al', 'albania'],
  '🇦🇲': ['flag-am', 'am', 'armenia'],
  '🇦🇴': ['flag-ao', 'ao', 'angola'],
  '🇦🇶': ['flag-aq', 'antarctica'],
  '🇦🇷': ['flag-ar', 'ar', 'argentina'],
  '🇦🇸': ['flag-as', 'as', 'american_samoa'],
  '🇦🇹': ['flag-at', 'at', 'austria'],
  '🇦🇺': ['flag-au', 'au', 'australia'],
  '🇦🇼': ['flag-aw', 'aw', 'aruba'],
  '🇦🇽': ['flag-ax', 'aland_islands', 'åland_islands'],
  '🇦🇿': ['flag-az', 'az', 'azerbaijan'],
  '🇧🇦': ['flag-ba', 'ba', 'bosnia_herzegovina', 'bosnia_&_herzegovina'],
  '🇧🇧': ['flag-bb', 'bb', 'barbados'],
  '🇧🇩': ['flag-bd', 'bd', 'bangladesh'],
  '🇧🇪': ['flag-be', 'be', 'belgium'],
  '🇧🇫': ['flag-bf', 'bf', 'burkina_faso'],
  '🇧🇬': ['flag-bg', 'bg', 'bulgaria'],
  '🇧🇭': ['flag-bh', 'bh', 'bahrain'],
  '🇧🇮': ['flag-bi', 'bi', 'burundi'],
  '🇧🇯': ['flag-bj', 'bj', 'benin'],
  '🇧🇱': ['flag-bl', 'st_barthelemy'],
  '🇧🇲': ['flag-bm', 'bm', 'bermuda'],
  '🇧🇳': ['flag-bn', 'bn', 'brunei'],
  '🇧🇴': ['flag-bo', 'bo', 'bolivia'],
  '🇧🇶': ['flag-bq', 'caribbean_netherlands'],
  '🇧🇷': ['flag-br', 'br', 'brazil'],
  '🇧🇸': ['flag-bs', 'bs', 'bahamas'],
  '🇧🇹': ['flag-bt', 'bt', 'bhutan'],
  '🇧🇻': ['flag-bv', 'bouvet_island'],
  '🇧🇼': ['flag-bw', 'bw', 'botswana'],
  '🇧🇾': ['flag-by', 'by', 'belarus'],
  '🇧🇿': ['flag-bz', 'bz', 'belize'],
  '🇨🇦': ['flag-ca', 'ca', 'canada'],
  '🇨🇨': ['flag-cc', 'cocos_islands', 'cocos_(keeling)_islands'],
  '🇨🇩': ['flag-cd', 'cd_flag', 'congo_kinshasa', 'congo_-_kinshasa'],
  '🇨🇫': ['flag-cf', 'cf', 'central_african_republic'],
  '🇨🇬': ['flag-cg', 'cg', 'congo_brazzaville', 'congo_-_brazzaville'],
  '🇨🇭': ['flag-ch', 'ch', 'switzerland'],
  '🇨🇮': ['flag-ci', 'ci', 'cote_divoire', 'côte_d’ivoire'],
  '🇨🇰': ['flag-ck', 'ck', 'cook_islands'],
  '🇨🇱': ['flag-cl', 'cl_flag', 'chile'],
  '🇨🇲': ['flag-cm', 'cm', 'cameroon'],
  '🇨🇳': ['flag-cn', 'cn', 'china'],
  '🇨🇴': ['flag-co', 'co', 'colombia'],
  '🇨🇵': ['flag-cp', 'clipperton_island'],
  '🇨🇷': ['flag-cr', 'cr', 'costa_rica'],
  '🇨🇺': ['flag-cu', 'cu', 'cuba'],
  '🇨🇻': ['flag-cv', 'cv', 'cape_verde'],
  '🇨🇼': ['flag-cw', 'cw', 'curacao', 'curaçao'],
  '🇨🇽': ['flag-cx', 'christmas_island'],
  '🇨🇾': ['flag-cy', 'cy', 'cyprus'],
  '🇨🇿': ['flag-cz', 'cz', 'czech_republic', 'czechia'],
  '🇩🇪': ['flag-de', 'de', 'germany'],
  '🇩🇬': ['flag-dg', 'diego_garcia'],
  '🇩🇯': ['flag-dj', 'dj', 'djibouti'],
  '🇩🇰': ['flag-dk', 'dk', 'denmark'],
  '🇩🇲': ['flag-dm', 'dm', 'dominica'],
  '🇩🇴': ['flag-do', 'do', 'dominican_republic'],
  '🇩🇿': ['flag-dz', 'dz', 'algeria'],
  '🇪🇦': ['flag-ea', 'ceuta_melilla', 'ceuta_&_melilla'],
  '🇪🇨': ['flag-ec', 'ec', 'ecuador'],
  '🇪🇪': ['flag-ee', 'ee', 'estonia'],
  '🇪🇬': ['flag-eg', 'eg', 'egypt'],
  '🇪🇭': ['flag-eh', 'western_sahara'],
  '🇪🇷': ['flag-er', 'er', 'eritrea'],
  '🇪🇸': ['flag-es', 'es', 'spain'],
  '🇪🇹': ['flag-et', 'et', 'ethiopia'],
  '🇪🇺': ['flag-eu', 'eu', 'european_union'],
  '🇫🇮': ['flag-fi', 'fi', 'finland'],
  '🇫🇯': ['flag-fj', 'fj', 'fiji'],
  '🇫🇰': ['flag-fk', 'falkland_islands'],
  '🇫🇲': ['flag-fm', 'micronesia'],
  '🇫🇴': ['flag-fo', 'fo', 'faroe_islands'],
  '🇫🇷': ['flag-fr', 'fr', 'france'],
  '🇬🇦': ['flag-ga', 'ga', 'gabon'],
  '🇬🇧': ['flag-gb', 'gb', 'uk', 'united_kingdom'],
  '🇬🇩': ['flag-gd', 'gd', 'grenada'],
  '🇬🇪': ['flag-ge', 'ge', 'georgia'],
  '🇬🇫': ['flag-gf', 'gf', 'french_guiana'],
  '🇬🇬': ['flag-gg', 'guernsey'],
  '🇬🇭': ['flag-gh', 'gh', 'ghana'],
  '🇬🇮': ['flag-gi', 'gi', 'gibraltar'],
  '🇬🇱': ['flag-gl', 'greenland'],
  '🇬🇲': ['flag-gm', 'gm', 'gambia'],
  '🇬🇳': ['flag-gn', 'gn', 'guinea'],
  '🇬🇵': ['flag-gp', 'gp', 'guadeloupe'],
  '🇬🇶': ['flag-gq', 'gq', 'equatorial_guinea'],
  '🇬🇷': ['flag-gr', 'gr', 'greece'],
  '🇬🇸': [
    'flag-gs',
    'south_georgia_south_sandwich_islands',
    'south_georgia_&_south_sandwich_islands',
  ],
  '🇬🇹': ['flag-gt', 'gt', 'guatemala'],
  '🇬🇺': ['flag-gu', 'gu', 'guam'],
  '🇬🇼': ['flag-gw', 'gw', 'guinea_bissau', 'guinea-bissau'],
  '🇬🇾': ['flag-gy', 'gy', 'guyana'],
  '🇭🇰': ['flag-hk', 'hk', 'hong_kong', 'hong_kong_sar_china'],
  '🇭🇲': ['flag-hm', 'heard_mcdonald_islands', 'heard_&_mcdonald_islands'],
  '🇭🇳': ['flag-hn', 'hn', 'honduras'],
  '🇭🇷': ['flag-hr', 'hr', 'croatia'],
  '🇭🇹': ['flag-ht', 'ht', 'haiti'],
  '🇭🇺': ['flag-hu', 'hu', 'hungary'],
  '🇮🇨': ['flag-ic', 'canary_islands'],
  '🇮🇩': ['flag-id', 'id_flag', 'indonesia'],
  '🇮🇪': ['flag-ie', 'ie', 'ireland'],
  '🇮🇱': ['flag-il', 'il', 'israel'],
  '🇮🇲': ['flag-im', 'isle_of_man'],
  '🇮🇳': ['flag-in', 'in', 'india'],
  '🇮🇴': ['flag-io', 'british_indian_ocean_territory'],
  '🇮🇶': ['flag-iq', 'iq', 'iraq'],
  '🇮🇷': ['flag-ir', 'ir', 'iran'],
  '🇮🇸': ['flag-is', 'is', 'iceland'],
  '🇮🇹': ['flag-it', 'it', 'italy'],
  '🇯🇪': ['flag-je', 'jersey'],
  '🇯🇲': ['flag-jm', 'jm', 'jamaica'],
  '🇯🇴': ['flag-jo', 'jo', 'jordan'],
  '🇯🇵': ['flag-jp', 'jp'],
  '🇰🇪': ['flag-ke', 'ke', 'kenya'],
  '🇰🇬': ['flag-kg', 'kg', 'kyrgyzstan'],
  '🇰🇭': ['flag-kh', 'kh', 'cambodia'],
  '🇰🇮': ['flag-ki', '2', 'kiribati'],
  '🇰🇲': ['flag-km', 'km', 'comoros'],
  '🇰🇳': ['flag-kn', 'st_kitts_nevis'],
  '🇰🇵': ['flag-kp', 'kp', 'north_korea'],
  '🇰🇷': ['flag-kr', 'kr', 'south_korea'],
  '🇰🇼': ['flag-kw', 'kw', 'kuwait'],
  '🇰🇾': ['flag-ky', 'ky', 'cayman_islands'],
  '🇰🇿': ['flag-kz', 'kz', 'kazakhstan'],
  '🇱🇦': ['flag-la', 'la', 'laos'],
  '🇱🇧': ['flag-lb', 'lb', 'lebanon'],
  '🇱🇨': ['flag-lc', 'st_lucia'],
  '🇱🇮': ['flag-li', 'li', 'liechtenstein'],
  '🇱🇰': ['flag-lk', 'lk', 'sri_lanka'],
  '🇱🇷': ['flag-lr', 'lr', 'liberia'],
  '🇱🇸': ['flag-ls', 'ls', 'lesotho'],
  '🇱🇹': ['flag-lt', 'lt', 'lithuania'],
  '🇱🇺': ['flag-lu', 'lu', 'luxembourg'],
  '🇱🇻': ['flag-lv', 'lv', 'latvia'],
  '🇱🇾': ['flag-ly', 'ly', 'libya'],
  '🇲🇦': ['flag-ma', 'ma', 'morocco'],
  '🇲🇨': ['flag-mc', 'monaco'],
  '🇲🇩': ['flag-md', 'md', 'moldova'],
  '🇲🇪': ['flag-me', 'me', 'montenegro'],
  '🇲🇫': ['flag-mf', 'st_martin'],
  '🇲🇬': ['flag-mg', 'mg', 'madagascar'],
  '🇲🇭': ['flag-mh', 'marshall_islands'],
  '🇲🇰': ['flag-mk', 'mk', 'macedonia'],
  '🇲🇱': ['flag-ml', 'ml', 'mali'],
  '🇲🇲': ['flag-mm', 'mm', 'myanmar', 'myanmar_(burma)'],
  '🇲🇳': ['flag-mn', 'mn', 'mongolia'],
  '🇲🇴': ['flag-mo', 'mo', 'macau', 'macao_sar_china'],
  '🇲🇵': ['flag-mp', 'mp', 'northern_mariana_islands'],
  '🇲🇶': ['flag-mq', 'mq', 'martinique'],
  '🇲🇷': ['flag-mr', 'mr', 'mauritania'],
  '🇲🇸': ['flag-ms', 'ms', 'montserrat'],
  '🇲🇹': ['flag-mt', 'mt', 'malta'],
  '🇲🇺': ['flag-mu', 'mauritius'],
  '🇲🇻': ['flag-mv', 'mv', 'maldives'],
  '🇲🇼': ['flag-mw', 'mw', 'malawi'],
  '🇲🇽': ['flag-mx', 'mx', 'mexico'],
  '🇲🇾': ['flag-my', 'my', 'malaysia'],
  '🇲🇿': ['flag-mz', 'mz', 'mozambique'],
  '🇳🇦': ['flag-na', 'na', 'namibia'],
  '🇳🇨': ['flag-nc', 'nc', 'new_caledonia'],
  '🇳🇪': ['flag-ne', 'ne', 'niger'],
  '🇳🇫': ['flag-nf', 'norfolk_island'],
  '🇳🇬': ['flag-ng', 'nigeria'],
  '🇳🇮': ['flag-ni', 'ni', 'nicaragua'],
  '🇳🇱': ['flag-nl', 'nl', 'netherlands'],
  '🇳🇴': ['flag-no', 'no', 'norway'],
  '🇳🇵': ['flag-np', 'np', 'nepal'],
  '🇳🇷': ['flag-nr', 'nauru'],
  '🇳🇺': ['flag-nu', 'nu', 'niue'],
  '🇳🇿': ['flag-nz', 'nz', 'new_zealand'],
  '🇴🇲': ['flag-om', 'om', 'oman'],
  '🇵🇦': ['flag-pa', 'pa', 'panama'],
  '🇵🇪': ['flag-pe', 'pe', 'peru'],
  '🇵🇫': ['flag-pf', 'french_polynesia'],
  '🇵🇬': ['flag-pg', 'pg', 'papua_new_guinea'],
  '🇵🇭': ['flag-ph', 'ph', 'philippines'],
  '🇵🇰': ['flag-pk', 'pk', 'pakistan'],
  '🇵🇱': ['flag-pl', 'pl', 'poland'],
  '🇵🇲': ['flag-pm', 'st_pierre_miquelon'],
  '🇵🇳': ['flag-pn', 'pitcairn_islands'],
  '🇵🇷': ['flag-pr', 'pr', 'puerto_rico'],
  '🇵🇸': ['flag-ps', 'ps', 'palestinian_territories'],
  '🇵🇹': ['flag-pt', 'pt', 'portugal'],
  '🇵🇼': ['flag-pw', 'pw', 'palau'],
  '🇵🇾': ['flag-py', 'py', 'paraguay'],
  '🇶🇦': ['flag-qa', 'qa', 'qatar'],
  '🇷🇪': ['flag-re', 're', 'reunion', 'réunion'],
  '🇷🇴': ['flag-ro', 'ro', 'romania'],
  '🇷🇸': ['flag-rs', 'rs', 'serbia'],
  '🇷🇺': ['flag-ru', 'ru', 'russia'],
  '🇷🇼': ['flag-rw', 'rw', 'rwanda'],
  '🇸🇦': ['flag-sa', 'sa_flag', 'saudi_arabia'],
  '🇸🇧': ['flag-sb', 'sb', 'solomon_islands'],
  '🇸🇨': ['flag-sc', 'sc', 'seychelles'],
  '🇸🇩': ['flag-sd', 'sd', 'sudan'],
  '🇸🇪': ['flag-se', 'se', 'sweden'],
  '🇸🇬': ['flag-sg', 'sg', 'singapore'],
  '🇸🇭': ['flag-sh', 'st_helena'],
  '🇸🇮': ['flag-si', 'si', 'slovenia'],
  '🇸🇯': ['flag-sj', 'svalbard_jan_mayen', 'svalbard_&_jan_mayen'],
  '🇸🇰': ['flag-sk', 'sk', 'slovakia'],
  '🇸🇱': ['flag-sl', 'sl', 'sierra_leone'],
  '🇸🇲': ['flag-sm', 'sm', 'san_marino'],
  '🇸🇳': ['flag-sn', 'sn', 'senegal'],
  '🇸🇴': ['flag-so', 'so', 'somalia'],
  '🇸🇷': ['flag-sr', 'sr', 'suriname'],
  '🇸🇸': ['flag-ss', 'ss', 'south_sudan'],
  '🇸🇹': ['flag-st', 'st', 'sao_tome_principe', 'são_tomé_&_príncipe'],
  '🇸🇻': ['flag-sv', 'sv', 'el_salvador'],
  '🇸🇽': ['flag-sx', 'sint_maarten'],
  '🇸🇾': ['flag-sy', 'sy', 'syria'],
  '🇸🇿': ['flag-sz', 'sz', 'swaziland', 'eswatini'],
  '🇹🇦': ['flag-ta', 'tristan_da_cunha'],
  '🇹🇨': ['flag-tc', 'tc', 'turks_caicos_islands', 'turks_&_caicos_islands'],
  '🇹🇩': ['flag-td', 'chad'],
  '🇹🇫': ['flag-tf', 'tf', 'french_southern_territories'],
  '🇹🇬': ['flag-tg', 'tg', 'togo'],
  '🇹🇭': ['flag-th', 'th', 'thailand'],
  '🇹🇯': ['flag-tj', 'tj', 'tajikistan'],
  '🇹🇰': ['flag-tk', 'tokelau'],
  '🇹🇱': ['flag-tl', 'tl', 'timor_leste', 'timor-leste'],
  '🇹🇲': ['flag-tm', 'tm_flag', 'turkmenistan'],
  '🇹🇳': ['flag-tn', 'tn', 'tunisia'],
  '🇹🇴': ['flag-to', 'to', 'tonga'],
  '🇹🇷': ['flag-tr', 'tr'],
  '🇹🇹': ['flag-tt', 'tt', 'trinidad_tobago', 'trinidad_&_tobago'],
  '🇹🇻': ['flag-tv', 'tv_flag', 'tuvalu'],
  '🇹🇼': ['flag-tw', 'taiwan'],
  '🇹🇿': ['flag-tz', 'tz', 'tanzania'],
  '🇺🇦': ['flag-ua', 'ua', 'ukraine'],
  '🇺🇬': ['flag-ug', 'ug', 'uganda'],
  '🇺🇲': ['flag-um', 'us_outlying_islands'],
  '🇺🇳': ['flag-un', 'united_nations'],
  '🇺🇸': ['flag-us', 'us', 'united_states'],
  '🇺🇾': ['flag-uy', 'uy', 'uruguay'],
  '🇺🇿': ['flag-uz', 'uz', 'uzbekistan'],
  '🇻🇦': ['flag-va', 'vatican_city'],
  '🇻🇨': ['flag-vc', 'vc', 'st_vincent_grenadines'],
  '🇻🇪': ['flag-ve', 've', 'venezuela'],
  '🇻🇬': ['flag-vg', 'vg', 'british_virgin_islands'],
  '🇻🇮': ['flag-vi', 'vi', 'us_virgin_islands'],
  '🇻🇳': ['flag-vn', 'vn', 'vietnam'],
  '🇻🇺': ['flag-vu', 'vu', 'vanuatu'],
  '🇼🇫': ['flag-wf', 'wallis_futuna', 'wallis_&_futuna'],
  '🇼🇸': ['flag-ws', 'ws', 'samoa'],
  '🇽🇰': ['flag-xk', 'kosovo'],
  '🇾🇪': ['flag-ye', 'ye', 'yemen'],
  '🇾🇹': ['flag-yt', 'mayotte'],
  '🇿🇦': ['flag-za', 'za', 'south_africa'],
  '🇿🇲': ['flag-zm', 'zm', 'zambia'],
  '🇿🇼': ['flag-zw', 'zw', 'zimbabwe'],
};
